/**
 * The 56 cards of the Minor Arcana — four suits of fourteen — with short,
 * original interpretations. For reflection and entertainment.
 */
import type { TarotCard, TarotDepth } from "./tarot";

export type Suit = "Wands" | "Cups" | "Swords" | "Pentacles";

export const SUITS: { suit: Suit; element: string; about: string }[] = [
  { suit: "Wands", element: "Fire", about: "Passion, creativity, ambition and action — the spark that gets things moving." },
  { suit: "Cups", element: "Water", about: "Feelings, love, relationships and intuition — the life of the heart." },
  { suit: "Swords", element: "Air", about: "Thoughts, words, truth and conflict — the power and the challenges of the mind." },
  { suit: "Pentacles", element: "Earth", about: "Money, work, home and the body — everything you can touch and build." },
];

const RANKS = ["Ace", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Page", "Knight", "Queen", "King"] as const;
const NUMERALS = ["A", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "P", "Kn", "Q", "K"];

// [keywords, upright, reversed, prompt, theme, meaning, love, work, spirit]
type Row = [string, string, string, string, string, string, string, string, string];

const DATA: Record<Suit, Row[]> = {
  Wands: [
    ["inspiration · new energy · potential", "A spark of inspiration arrives. Say yes to the idea that lights you up.", "The spark is there but stalled. Clear the doubts and let it catch.", "What idea keeps lighting you up?", "a new spark of passion", "The Ace of Wands is a hand bursting from the clouds holding a sprouting branch — raw creative fire. Something new wants to begin: a project, a passion, a fresh burst of confidence. Don't wait for perfect conditions; act while the energy is hot.", "Desire is rekindled. Chemistry and excitement are in the air.", "A new venture or idea has real potential. Start now.", "Your creative life force is strong — channel it into ritual or art."],
    ["planning · future vision · decisions", "You're looking out at your options. Make a bold plan for what comes next.", "Fear of the unknown keeps you playing small. The world is bigger than your comfort zone.", "If you weren't afraid, which way would you go?", "planning a bold next step", "The Two of Wands holds the world in one hand and looks to the horizon. You've had the spark; now you're deciding where to take it. This is a card of vision and planning. Think bigger than feels comfortable — the path you choose now shapes the months ahead.", "Decide what you really want rather than drifting.", "Map out your goals. Expansion or travel may be part of the plan.", "Set an intention for the long term, not just the next week."],
    ["expansion · progress · looking ahead", "Your efforts are starting to pay off. Ships are coming in.", "Delays and frustrations. Re-check your plans and be patient.", "What are you waiting to arrive — and how can you prepare for it?", "growth on the horizon", "The Three of Wands stands on a cliff watching ships sail out to sea. You've started something, and now you can see it growing. Opportunities may come from far away. Keep your vision wide, and be ready to step into the bigger life you've been building.", "A relationship grows, or someone from afar enters the picture.", "Projects expand. Think about new markets, partners or travel.", "Trust that what you've set in motion is unfolding."],
    ["celebration · home · harmony", "A joyful milestone. Celebrate with the people you love.", "Tension at home or a celebration that feels hollow. Find your sense of belonging.", "Who would you invite to your celebration?", "celebration and belonging", "The Four of Wands shows a garland-covered arch and people dancing beneath it. It's a card of happy milestones — homecomings, engagements, a project finished, a home that finally feels like yours. Stop and celebrate; joy shared is joy multiplied.", "Commitment, a celebration or meeting family. Love feels stable and happy.", "Team success. Mark the milestone before rushing on.", "Create a sacred space at home that feels like a sanctuary."],
    ["competition · conflict · friction", "Lots of voices, lots of egos. Healthy competition can sharpen you.", "Avoiding conflict, or a battle that's become pointless. Find common ground.", "What are you really fighting for?", "friction and competing energies", "In the Five of Wands, five people clash with their staffs — but no one seems hurt. This is everyday friction: disagreements, rivalry, too many opinions. Use it to clarify what you believe and to grow stronger, without taking it too personally.", "Petty arguments. Listen as much as you speak.", "Competition in the workplace. Stand your ground with grace.", "Inner conflict. Let your different wants be heard before you choose."],
    ["victory · recognition · confidence", "You've won — and people notice. Enjoy the recognition.", "Fear of failing, or success that went to your head. Stay humble and keep going.", "How do you want to be seen right now?", "public victory", "The Six of Wands rides through a cheering crowd wearing a laurel wreath. It's a card of success, praise and well-earned confidence. Let yourself be seen. Celebrate your wins out loud; they inspire others too.", "You feel admired and appreciated. Confidence is attractive.", "Recognition, promotion or a public win.", "Honour how far you've come — you're allowed to shine."],
    ["standing your ground · courage · defence", "Hold your position. You're on higher ground than you think.", "Feeling overwhelmed or giving in too easily. Choose which battles matter.", "What's worth defending in your life?", "standing firm in your truth", "The Seven of Wands defends a hilltop against challengers below. When you're successful or stand for something, people will push back. This card asks you to stay brave and protect your boundaries and beliefs — you have the advantage.", "Protect your heart, but don't build walls against everyone.", "Defend your ideas and your worth. Don't back down.", "Boundaries are a spiritual practice. Guard your energy."],
    ["speed · movement · news", "Things are moving fast. Messages, travel and quick progress.", "Delays, crossed wires or rushing. Slow down and check the details.", "What is ready to move quickly now?", "swift momentum", "The Eight of Wands shows eight staffs flying through the sky — everything is in motion. News arrives, plans accelerate and the waiting is over. Go with the flow and act quickly while the energy is with you.", "Messages, flirtation and fast-moving feelings. Things could heat up quickly.", "Rapid progress. Emails, calls and decisions come thick and fast.", "Your manifestations are speeding towards you."],
    ["resilience · persistence · the last stretch", "You're tired but nearly there. Keep going — you're stronger than you feel.", "Exhaustion or paranoia. Rest, and stop expecting the worst.", "What has made you stronger this year?", "resilience in the final stretch", "The Nine of Wands is wounded but still standing, staff in hand. You've been through a lot and you're cautious now. This card honours your resilience. One last push is needed; protect your energy and don't give up just before the finish line.", "Past hurts make you guarded. Let the right people in.", "You're almost done. Persevere, but ask for support.", "Your resilience is sacred. Rest is part of the fight."],
    ["burden · responsibility · overload", "You're carrying too much. Some of it isn't yours to carry.", "Putting down what's too heavy. Delegate and let go.", "What could you put down today?", "carrying too much", "The Ten of Wands shows someone bent under a bundle of staffs, struggling towards home. Success has brought responsibility — maybe too much. This card asks you to look honestly at your load. What can you share, delegate or drop entirely?", "One person is doing all the work. Rebalance the relationship.", "Burnout risk. Say no, delegate and simplify.", "Release obligations that drain your spirit."],
    ["curiosity · enthusiasm · new ideas", "An exciting idea or message arrives. Explore it with a curious heart.", "Scattered ideas or lack of direction. Pick one and see it through.", "What are you curious about right now?", "playful curiosity", "The Page of Wands gazes at a sprouting staff with wonder. Pages are messengers and beginners. This one brings enthusiasm, new passions and a free spirit. Try something new just because it excites you — no need to be an expert yet.", "Flirty, playful energy or exciting news from a love interest.", "Learning a new skill or exploring a creative idea.", "Approach your spiritual path with wonder and play."],
    ["passion · adventure · impulsiveness", "Full speed ahead! Passion and boldness carry you forward.", "Hasty, reckless or burnt out. Channel the fire before it consumes you.", "Where do you need more daring — or more patience?", "fiery adventure", "The Knight of Wands charges ahead on a rearing horse. He's passionate, adventurous and a little impatient. This card brings energy to make big moves — travel, change, bold action. Just make sure you know where you're heading before you gallop off.", "Intense attraction, but it may burn hot and fast.", "Take bold action. Great for launches, less for patience.", "Let passion fuel your practice — dance, move, create."],
    ["confidence · warmth · determination", "Magnetic, warm and confident. Own your power and your light.", "Insecurity or jealousy. Reconnect with what makes you shine.", "What makes you feel most like yourself?", "radiant confidence", "The Queen of Wands sits with a sunflower and a black cat — vibrant, independent and deeply self-assured. She knows her worth and lights up any room. This card asks you to embody that energy: be bold, be warm and don't dim your light for anyone.", "You're magnetic. Lead with confidence and warmth.", "Step into leadership with charisma and creativity.", "Your inner witch is powerful. Trust your magic."],
    ["vision · leadership · entrepreneurship", "A natural leader with a big vision. Take charge and inspire others.", "Domineering or impulsive. Lead with heart, not ego.", "What vision would you lead people towards?", "visionary leadership", "The King of Wands holds his staff like a sceptre, gazing into the future. He's an entrepreneur, a visionary and a natural leader. This card asks you to turn your passion into something lasting — set the direction and trust yourself to lead.", "A passionate, committed partner — or the call to lead in love.", "Lead with vision. Ideal for business and big decisions.", "Take responsibility for your spiritual path and help others on theirs."],
  ],
  Cups: [
    ["love · new feelings · compassion", "Your heart is opening. New love, friendship or emotional healing flows in.", "Blocked feelings or self-neglect. Fill your own cup first.", "Where is your heart overflowing?", "an overflowing heart", "The Ace of Cups is a chalice overflowing with water, a dove descending above it. It's the beginning of love in every form — romance, friendship, compassion, creativity and self-love. Let yourself feel deeply. Your heart is ready to receive.", "New love or a deepening connection. Open your heart.", "Creative work that comes from the heart flourishes.", "Spiritual awakening through love. Work with water and moon rituals."],
    ["partnership · connection · mutual attraction", "A beautiful connection based on respect and attraction.", "Imbalance or disconnection in a relationship. Talk honestly.", "What makes a connection feel equal to you?", "a soul connection", "The Two of Cups shows two people exchanging cups beneath a winged lion. It's the card of partnership — romantic, platonic or professional — where both people give and both receive. Mutual respect and attraction are the heart of it.", "A loving union or a meaningful new relationship.", "A strong partnership or collaboration.", "Harmony between your inner masculine and feminine."],
    ["friendship · celebration · community", "Gather your girls. Friendship, laughter and celebration.", "Overindulgence or feeling left out. Find your true circle.", "Who makes you feel most like yourself?", "sisterhood and celebration", "The Three of Cups shows three women raising their cups in a dance. It's the joy of friendship, community and shared celebration. Spend time with people who lift you up — this is a card of sisterhood and good times.", "Social occasions bring love. Celebrate with friends.", "Teamwork and celebrating a group success.", "Find your coven — magic is stronger in community."],
    ["contemplation · apathy · reevaluation", "You're bored or withdrawn and might miss what's being offered. Look up.", "Coming out of a slump. You're ready to engage again.", "What might you be overlooking?", "a gift being overlooked", "In the Four of Cups, someone sits under a tree staring at three cups, ignoring a fourth offered from a cloud. It's a card of introspection — sometimes healthy, sometimes a rut. Take time to reflect, but don't let apathy make you miss a gift.", "Taking love for granted, or needing space to think.", "Feeling uninspired. Look for the opportunity in front of you.", "Meditation helps — just don't disappear completely."],
    ["grief · loss · regret", "You're focused on what's been lost. Grieve, then notice what remains.", "Acceptance and moving on. Healing has begun.", "What is still standing for you?", "grief and what remains", "The Five of Cups shows a cloaked figure mourning three spilled cups, not seeing the two still full behind them. Loss and disappointment are real and need to be felt. When you're ready, turn around: something precious remains.", "Heartbreak or regret. Let yourself feel it, then forgive.", "A setback. Learn from it and look at what's left.", "Grief is sacred. Hold a ritual to honour what you've lost."],
    ["nostalgia · childhood · innocence", "Sweet memories, old friends or a return to simple joys.", "Stuck in the past. Bring the lessons forward, not the longing.", "What memory brings you comfort — and what does it teach you?", "sweet nostalgia", "The Six of Cups shows children sharing cups of flowers in a garden. It's a card of nostalgia, innocence and kindness. Someone from your past may reappear, or you may revisit a happy memory. Reconnect with your inner child's simple joys.", "An old flame or a sweet, innocent connection.", "Revisiting past skills or a former workplace.", "Inner child healing. Play, as you did when you were small."],
    ["choices · illusion · daydreaming", "So many options, some of them fantasies. Look closely before you choose.", "Clarity arrives. You see through the illusions.", "Which of your dreams is real — and which is a mirage?", "choices and illusions", "In the Seven of Cups, a figure stares at seven cups floating in the clouds, each filled with something different — treasure, a snake, a castle, a wreath. Too many options can paralyse you, and not all of them are what they seem. Ground your choices in reality.", "Don't idealise. See the person as they really are.", "Too many ideas. Choose one and make it real.", "Your imagination is a gift — anchor visions with action."],
    ["walking away · searching · moving on", "It's time to leave what no longer fulfils you, even if it looks fine on the surface.", "Fear of leaving, or drifting without purpose. Be honest about what you want.", "What are you ready to walk away from?", "walking away to find more", "The Eight of Cups shows someone walking away from eight neatly stacked cups, into the mountains under the moon. Something is missing, and you know it. This card honours the courage to leave the familiar in search of deeper meaning.", "Leaving a relationship that no longer nourishes you.", "Seeking more meaningful work.", "A spiritual quest begins. Follow the moon."],
    ["wishes · contentment · satisfaction", "The wish card! What you hoped for is coming true. Enjoy it.", "Wanting more, or smugness. True contentment comes from within.", "What would make you feel truly satisfied?", "a wish come true", "The Nine of Cups shows a contented figure seated before a row of nine cups. It's known as the wish card — emotional and material satisfaction, pleasure and gratitude. Make your wish, enjoy your blessings and let yourself feel fulfilled.", "Happiness in love. Your wish may come true.", "Satisfaction and success. Enjoy the rewards.", "Gratitude multiplies your blessings. Make a wish tonight."],
    ["harmony · family · emotional fulfilment", "Lasting happiness, family harmony and love that feels like home.", "Family tension or broken expectations. Talk with love.", "What does 'happily ever after' look like for you?", "lasting happiness", "The Ten of Cups shows a family under a rainbow of cups, children dancing. It's emotional fulfilment and harmony — a home and relationships full of love. Whatever your idea of family is, this card blesses it.", "Deep, lasting love and a happy home.", "Fulfilling work that supports your family life.", "Contentment. You are exactly where you belong."],
    ["creativity · intuition · sweet messages", "A tender message or creative idea surprises you. Stay open.", "Emotional immaturity or creative block. Be gentle with yourself.", "What is your intuition whispering?", "a sweet surprise of the heart", "The Page of Cups gazes at a fish leaping out of his cup — an unexpected message from the imagination. This card brings sweet news, creative ideas and intuitive nudges. Be open, a little whimsical and willing to believe in magic.", "A sweet message or new romantic interest.", "A creative opportunity. Trust your imagination.", "Intuitive messages come through dreams and signs."],
    ["romance · charm · following the heart", "Romance and invitations. Follow your heart's lead.", "Moodiness or unrealistic ideals. Keep both feet on the ground.", "Where is your heart asking you to go?", "following your heart", "The Knight of Cups rides slowly, holding out a cup like an offering. He's the romantic of the deck — charming, creative and led by feelings. An invitation, proposal or heartfelt offer may come your way.", "A romantic proposal or declaration. Swoon-worthy energy.", "An offer that speaks to your heart.", "Follow your feelings — they're leading you true."],
    ["compassion · intuition · emotional depth", "Lead with empathy and trust your deep intuition.", "Giving too much or losing yourself in others' feelings. Protect your energy.", "How can you care for yourself as tenderly as you care for others?", "deep compassion and intuition", "The Queen of Cups sits at the water's edge holding an ornate, closed cup. She's deeply intuitive, compassionate and emotionally wise. This card asks you to honour your feelings, hold space for others and trust what you sense beneath the surface.", "Emotional depth and nurturing love.", "Use empathy and intuition in your work.", "Your psychic gifts are strong. Trust them."],
    ["emotional balance · calm · diplomacy", "Calm in the storm. Balance feeling with wisdom.", "Emotional manipulation or repressed feelings. Let yourself feel.", "How can you stay calm without shutting down?", "calm emotional mastery", "The King of Cups sits on a throne floating on a choppy sea, perfectly calm. He feels deeply but isn't ruled by his emotions. This card asks you to stay compassionate and steady, especially when others are struggling.", "A mature, caring partner, or being that steady love yourself.", "Lead with diplomacy and emotional intelligence.", "Mastery of emotions is true power."],
  ],
  Swords: [
    ["clarity · truth · breakthrough", "A breakthrough moment. The truth cuts through confusion.", "Confusion or harsh words. Think before you speak.", "What truth is ready to be spoken?", "a breakthrough of clarity", "The Ace of Swords is a sword raised through the clouds, crowned with a wreath. It's mental clarity, truth and new ideas that cut through confusion. You see things as they are. Speak honestly and make clear decisions.", "Honest communication brings clarity.", "A brilliant idea or clear decision.", "Clarity of mind supports clarity of spirit."],
    ["indecision · stalemate · avoidance", "You're stuck between two choices, blindfolded. Something has to give.", "Information arrives and the stalemate breaks.", "What are you avoiding looking at?", "a difficult decision", "The Two of Swords shows a blindfolded woman holding two crossed swords, the sea behind her. You're avoiding a decision, perhaps to keep the peace. But avoiding a choice is still a choice. Remove the blindfold and let your heart weigh in.", "Avoiding a conversation or decision.", "A stalemate. Gather facts, then decide.", "Meditate to quiet the mind and hear your inner voice."],
    ["heartbreak · sorrow · painful truth", "Painful truth or heartbreak. Feel it; healing begins when you do.", "Recovering from hurt. Forgiveness opens the way.", "What needs healing in your heart?", "heartbreak and release", "The Three of Swords is a heart pierced by three swords in the rain. It's one of the most honest cards — sorrow, grief or painful truth. Don't rush the healing. Cry, journal and let the storm pass. Clear skies follow.", "Heartbreak or painful honesty.", "Disappointment. Process it before moving on.", "Use tears as release. Water cleanses."],
    ["rest · recovery · contemplation", "Rest. Your mind and body need time out to recover.", "Restlessness or burnout. You can't pour from an empty cup.", "When did you last truly rest?", "rest and recovery", "The Four of Swords shows a knight lying at rest in a quiet chapel. After stress, you need recovery. This card prescribes rest, meditation and solitude — not giving up, but recharging so you can return stronger.", "Take a breather from relationship stress.", "Take time off or slow down.", "Meditation and sleep are your magic now."],
    ["conflict · winning at a cost · ego", "Winning the argument may cost you more than it's worth.", "Making peace after conflict. Let go of needing to be right.", "Is being right worth it here?", "a hollow victory", "The Five of Swords shows someone collecting swords while others walk away defeated. Conflict, ego and winning at all costs. Ask yourself what victory really means here, and whether some battles are better left unfought.", "Arguments with no winner. Choose peace.", "Office politics or tension. Rise above it.", "Release the need to be right."],
    ["transition · moving on · calmer waters", "Moving towards calmer waters. A difficult time is behind you.", "Resistance to change or unfinished business.", "What are you leaving behind on the shore?", "moving to calmer waters", "The Six of Swords shows a boat carrying people across the water from rough seas to calm. It's a transition — leaving a hard situation for something better. The journey may be quiet and a little sad, but it's taking you somewhere peaceful.", "Moving on from a difficult relationship or into calmer love.", "A transition or relocation for the better.", "A healing journey. Travel near water helps."],
    ["strategy · secrecy · cunning", "Someone may not be telling the whole truth — or you need to be strategic.", "Coming clean, or a plan revealed. Honesty is easier.", "Where are you being less than honest — with others or yourself?", "secrets and strategy", "The Seven of Swords shows a figure sneaking away from a camp carrying five swords. It can mean deception, but also strategy — doing things your own way. Be wise, protect your interests and be honest about your own motives.", "Watch for secrets or half-truths.", "Strategise carefully. Keep plans private for now.", "Be honest with yourself about what you're avoiding."],
    ["restriction · self-limiting beliefs · feeling trapped", "You feel trapped, but the bindings are loose. Your thoughts are the cage.", "Breaking free from limiting beliefs.", "What belief is keeping you stuck?", "self-imposed limits", "The Eight of Swords shows a blindfolded woman surrounded by swords — but there's a clear way out. This card is about feeling trapped by circumstances or beliefs. Once you change your thinking, you'll see you're freer than you feel.", "Feeling stuck in a situation you can leave.", "You have more options than you think.", "Shadow work around limiting beliefs is powerful."],
    ["anxiety · worry · sleepless nights", "Worries keep you up at night. Most of them aren't as bad in daylight.", "Anxiety easing. Reach out — you don't have to face it alone.", "What would you say to a friend with this worry?", "worry and sleepless nights", "The Nine of Swords shows someone sitting up in bed, head in hands. Anxiety and fear feel huge at 3am. This card asks you to name your worries, share them and remember that your mind can be your harshest critic.", "Anxiety about love. Talk it through.", "Stress and overthinking. Write it all down.", "Calming rituals — lavender, breathwork, a gentle night routine."],
    ["endings · rock bottom · release", "A painful ending — but it's the end. The only way is up.", "Recovery and rising after a hard fall.", "What has finally ended — and what can begin?", "a hard ending and new dawn", "The Ten of Swords shows a figure lying under ten swords as the sun rises behind them. It's dramatic: rock bottom, a painful end. But the dawn is coming. This is the final chapter of something difficult — let it close.", "A relationship is truly over. Healing comes next.", "A painful ending makes way for something new.", "Surrender. The darkest hour is before dawn."],
    ["curiosity · new ideas · communication", "A curious mind and new ideas. Ask questions and learn.", "Gossip or speaking without thinking. Choose your words.", "What do you want to learn more about?", "a curious mind", "The Page of Swords stands alert, sword raised, wind in the trees. Pages are students and messengers; this one brings curiosity, sharp ideas and lots of questions. Learn, research and speak up — but listen too.", "Honest, curious communication. Ask, don't assume.", "Research, learning and new ideas.", "Study a new area of your craft."],
    ["ambition · action · fast thinking", "Charge ahead with conviction. Fast decisions and bold words.", "Impatience or rudeness. Slow down and think.", "Where are you rushing — and where should you charge?", "fast, bold action", "The Knight of Swords races into battle on a galloping horse. He's driven, ambitious and quick-thinking — sometimes too quick. This card brings energy to pursue your goals, as long as you don't trample others on the way.", "Direct communication, sometimes too blunt.", "Act decisively and quickly.", "Focus your mind like a blade."],
    ["independence · honesty · clear boundaries", "Clear-headed, honest and independent. Speak your truth with kindness.", "Coldness or bitterness. Soften, without losing clarity.", "Where do you need clearer boundaries?", "clear-eyed truth", "The Queen of Swords sits upright, sword raised, one hand extended. She's been through hardship and come out wise and honest. This card asks you to set clear boundaries, speak your truth and not let emotion cloud your judgement.", "Independence and honesty in love.", "Use your clarity and experience. Be direct.", "Wisdom from past pain is a gift."],
    ["authority · intellect · truth", "Lead with logic and fairness. Your clear mind is your power.", "Manipulation or harsh judgement. Balance head and heart.", "How can you use your mind to serve others?", "wise authority", "The King of Swords sits on his throne, sword upright, calm and decisive. He's intellectual, fair and in command of his thoughts. This card asks you to make decisions based on truth and ethics, not emotion.", "A clear-headed partner, or a mature, honest talk.", "Leadership, expertise and fair decisions.", "Mental discipline supports spiritual growth."],
  ],
  Pentacles: [
    ["new opportunity · prosperity · manifestation", "A new opportunity for money, work or health. Plant the seed.", "A missed chance or poor planning. Get practical.", "What would you like to grow in the material world?", "a seed of prosperity", "The Ace of Pentacles is a hand holding a golden coin above a blooming garden. It's a new beginning in the physical world — money, a job, a home, better health. Plant this seed with care and it can grow into real abundance.", "Love with real stability. Something solid begins.", "A new job, client or financial opportunity.", "Manifestation through grounded, practical magic."],
    ["balance · juggling · adaptability", "You're juggling a lot. Stay flexible and keep your balance.", "Overwhelm or poor priorities. Drop a ball or two.", "What are you trying to keep in the air?", "a juggling act", "The Two of Pentacles shows someone juggling two coins in an infinity loop while ships ride the waves behind. Life is busy and you're managing many priorities. Stay adaptable, keep a sense of humour and remember balance is a practice.", "Balancing love with everything else.", "Multitasking. Prioritise and keep track of money.", "Flow with change, like the tides."],
    ["teamwork · skill · collaboration", "Working together brings something beautiful to life.", "Poor teamwork or lack of effort.", "Who could help you build what you're dreaming of?", "skilled collaboration", "The Three of Pentacles shows a craftsman working in a cathedral, discussing plans with others. It's about skill, teamwork and building something meaningful together. Your talent is recognised — and collaboration makes it greater.", "Building a relationship together, step by step.", "Collaboration and recognition for your skills.", "Learn from others in your spiritual community."],
    ["security · saving · holding on", "Security matters — but don't grip so tightly that nothing can flow.", "Letting go of control, or overspending. Find the middle.", "What are you holding on to too tightly?", "holding on for security", "The Four of Pentacles shows a figure clutching coins — one on his head, one in his arms, two under his feet. It's about security and saving, but also fear of loss. Protect what matters while letting abundance flow in and out.", "Possessiveness or fear of being hurt. Open up.", "Saving and stability. Don't let fear block opportunities.", "Abundance flows. Release scarcity thinking."],
    ["hardship · insecurity · isolation", "A hard time, financially or emotionally. Help is closer than you think.", "Recovery after hardship. Accept support.", "Where could you ask for help?", "hardship and seeking help", "The Five of Pentacles shows two figures struggling through snow past a glowing church window. It's a card of hardship and feeling left out in the cold. Remember: help is right there, if you're willing to ask.", "Feeling unloved or left out. Reach out.", "Money worries. Seek advice or support.", "Spiritual support is available. Ask for it."],
    ["generosity · giving · receiving", "Give and receive with grace. Generosity comes full circle.", "Strings attached or one-sided giving.", "Where can you give — or receive — more freely?", "generosity and exchange", "The Six of Pentacles shows a merchant weighing coins and giving to those in need. It's about generosity, charity and fair exchange. Whether you're giving or receiving, let it flow with an open heart.", "Balance in giving and receiving love.", "Fair pay, bonuses or help from a mentor.", "Acts of kindness are magic."],
    ["patience · long-term growth · investment", "Your efforts are growing, slowly. Be patient — harvest is coming.", "Impatience or wasted effort. Re-evaluate where you invest.", "What are you patiently growing?", "patient growth", "The Seven of Pentacles shows a gardener resting on a hoe, looking at a bush full of coins. You've worked hard and things are growing, but not as fast as you'd like. Pause, assess and trust the slow magic of time.", "Love that grows slowly is worth waiting for.", "Long-term investment and patience.", "Spiritual growth takes time. Keep tending."],
    ["mastery · diligence · craft", "Focused, dedicated work. You're mastering your craft.", "Perfectionism or lack of focus.", "What skill would you love to master?", "devoted craftsmanship", "The Eight of Pentacles shows an apprentice carefully carving coins at a workbench. It's dedication, practice and mastery. Keep showing up, keep learning — every small effort adds up to real skill.", "Putting effort into the relationship.", "Hard work, training and skill-building.", "Daily practice is how witches are made."],
    ["independence · luxury · self-sufficiency", "You've built a beautiful life. Enjoy the fruits of your labour.", "Overworking or financial dependence. Value yourself.", "How can you treat yourself today?", "self-made abundance", "The Nine of Pentacles shows an elegant woman in a lush garden, a falcon on her hand. She's independent, abundant and enjoying what she's created. Celebrate your self-sufficiency and indulge in a little luxury.", "Loving yourself first. Independence in love.", "Financial independence and well-earned reward.", "Abundance is your birthright. Enjoy it."],
    ["legacy · wealth · family", "Lasting wealth, family and legacy. Something built to last.", "Family disputes or financial instability.", "What legacy do you want to leave?", "lasting legacy", "The Ten of Pentacles shows three generations in an archway full of coins. It's about legacy, family, inheritance and long-term security. What you build now can bless future generations.", "Long-term commitment and family.", "Lasting success and financial security.", "Honour your ancestors and your roots."],
    ["learning · ambition · new skills", "A new opportunity to learn and grow. Study with dedication.", "Procrastination or lack of focus.", "What would you like to study or learn?", "eager learning", "The Page of Pentacles studies a coin held in front of him, in a fresh green field. It's the student of the deck — ambitious, practical and eager to learn. A new course, job or financial plan could be the start of something great.", "A grounded, sincere new connection.", "Study, training or a new job.", "Learn your craft step by step."],
    ["hard work · routine · reliability", "Slow and steady wins. Commit to your routine.", "Boredom or being stuck in a rut.", "Which routine is serving you — and which needs refreshing?", "steady reliability", "The Knight of Pentacles sits on a still horse, looking at a field. He's the most reliable knight — hardworking, patient and committed. This card asks for consistency: keep going, step by step.", "Loyal, dependable love.", "Hard work and routine bring results.", "Consistency in your practice brings power."],
    ["nurturing · abundance · practicality", "Nurturing, practical and abundant. Care for home, body and loved ones.", "Self-neglect or overwhelm. Look after yourself too.", "How can you make your home feel more nourishing?", "nurturing abundance", "The Queen of Pentacles sits in a lush garden, a rabbit at her feet. She's warm, grounded and abundant — a nurturer who also knows how to manage money and a home. Care for your body, your home and your loved ones, including yourself.", "A nurturing, grounded love.", "Balancing work and home beautifully.", "Kitchen witchery and earth magic suit you now."],
    ["wealth · success · security", "Abundance and success built through steady effort. Enjoy it wisely.", "Greed or obsession with status.", "What does true wealth mean to you?", "abundant success", "The King of Pentacles sits on a throne carved with bulls, surrounded by grapes and gold. He's achieved success through hard work and wisdom. This card brings financial security, generosity and leadership in the material world.", "A stable, generous partner.", "Business success and financial security.", "Use your abundance to bless others."],
  ],
};

const SUIT_SYMBOL: Record<Suit, string> = { Wands: "wands", Cups: "cups", Swords: "swords", Pentacles: "pentacles" };

/** Cards are numbered 22–77, following the Major Arcana (0–21). */
export const MINOR_ARCANA: (TarotCard & { suit: Suit })[] = [];
export const MINOR_DEPTH: Record<number, TarotDepth> = {};

let n = 22;
for (const { suit } of SUITS) {
  DATA[suit].forEach(([keywords, upright, reversed, prompt, theme, meaning, love, work, spirit], i) => {
    MINOR_ARCANA.push({ n, numeral: NUMERALS[i], name: `${RANKS[i]} of ${suit}`, symbol: SUIT_SYMBOL[suit], keywords, upright, reversed, prompt, suit });
    MINOR_DEPTH[n] = { theme, meaning, love, work, spirit };
    n++;
  });
}
